"""Add avatar_url

Revision ID: 80316ded488b
Revises: 85c6a992900c
Create Date: 2026-01-10 12:15:18.999468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80316ded488b'
down_revision: Union[str, None] = '85c6a992900c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debate_participants', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debate_participants', 'avatar_url')
    # ### end Alembic commands ###
